---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liyunhan.
--- DateTime: 2020/10/7 9:11 PM
---


array = {}
for i=1,3 do
    array[i] = {}
    for j=1,3 do
        array[i][j] = i*j
    end
end

local ret = math.floor(2100/524)
ret=ret%2







local queue = {}

function add()
    local rd={}
    rd.user=math.random(1,100)
    rd.amount=math.random(1,100)
    table.insert(queue,rd)
    local size=#queue
    if(size>5) then
        table.remove(queue,1)
    end
end

for i = 1, 20 do
    add()
    local a=""
end



local tbtest={}
tbtest[1]={}
tbtest[2]={}
tbtest[1].a=1
tbtest[2].a=1
local c=tbtest[1]
c=nil
tbtest[1]=c
local a=''


